-- ─────────────────────────────────────────────────────────────
-- FAO Event Registration Application — Supabase Database Schema
-- ─────────────────────────────────────────────────────────────

-- 1. REGISTRATION LIST TABLE
CREATE TABLE IF NOT EXISTS public.registration_list (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    registration_type TEXT,
    prefix TEXT,
    speaker_type TEXT,
    first_name TEXT,
    middle_initial TEXT,
    last_name TEXT,
    suffix TEXT,
    full_name TEXT,
    age_range TEXT,
    gender TEXT,
    nationality TEXT,
    affiliation TEXT,
    affiliation_sub TEXT,
    affiliation_specify TEXT,
    designation TEXT,
    media_queries TEXT,
    company TEXT,
    email TEXT UNIQUE NOT NULL,
    phone TEXT,
    address_country TEXT,
    address_state TEXT,
    address_street TEXT,
    address_city TEXT,
    address_zip TEXT,
    dietary TEXT,
    dietary_details TEXT,
    academic_type TEXT,
    attendance_mode TEXT,
    attendance_days TEXT,
    visa_assistance TEXT,
    field_trip TEXT,
    seminar TEXT,
    zoom_meeting_id TEXT,
    approval_status TEXT DEFAULT 'pending' NOT NULL
);

-- Enable Row Level Security (RLS) if desired, or leave open for simple REST API access
ALTER TABLE public.registration_list ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Enable all access for anon and authenticated users" 
ON public.registration_list FOR ALL 
USING (true) 
WITH CHECK (true);

-- 2. ATTENDANCE KEYS TABLE
CREATE TABLE IF NOT EXISTS public.attendance_keys (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    participant_id BIGINT REFERENCES public.registration_list(id) ON DELETE CASCADE,
    visitor_code TEXT,
    attendance_key TEXT
);

ALTER TABLE public.attendance_keys ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Enable all access for anon and authenticated users" 
ON public.attendance_keys FOR ALL 
USING (true) 
WITH CHECK (true);

-- 3. ZOOM REGISTRATIONS TABLE
CREATE TABLE IF NOT EXISTS public.zoom_registrations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    user_id BIGINT REFERENCES public.registration_list(id) ON DELETE CASCADE,
    join_url TEXT
);

ALTER TABLE public.zoom_registrations ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Enable all access for anon and authenticated users" 
ON public.zoom_registrations FOR ALL 
USING (true) 
WITH CHECK (true);

-- 4. ATTENDANCE LOGS TABLE
CREATE TABLE IF NOT EXISTS public.attendance_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    participant_id BIGINT REFERENCES public.registration_list(id) ON DELETE CASCADE,
    scanned_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    scanned_by TEXT
);

ALTER TABLE public.attendance_logs ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Enable all access for anon and authenticated users" 
ON public.attendance_logs FOR ALL 
USING (true) 
WITH CHECK (true);

